---

- name: Set up revaliases

  template:
    src: revaliases.j2
    dest: /etc/ssmtp/revaliases


- name: Change root user GECOS

  user:
    name: root
    comment: root {{ inventory_hostname }}

